name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy_backend:
    if: contains(github.event.head_commit.message, '[backend]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          echo "Deploying backend to Render..."
          # Здесь добавьте команду для деплоя на Render

  deploy_frontend:
    if: contains(github.event.head_commit.message, '[frontend]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        run: |
          echo "Deploying frontend to Vercel..."
          # Здесь добавьте команду для деплоя на Vercel
